version: latest
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SERVERURL=167.48.0.2 #optional
      - PEERS=
      - SERVERPORT=44556 #optional
      - ALLOWEDIPS=172.19.0.0/16 #optional
      - LOG_CONFS=true #optional
    volumes:
      - ./config:/config
      - ./modules:/lib/modules #optional
    ports:
      - 44556:44556/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      my-network:
        ipv4_address: 167.48.0.2

  
  ubuntu:
      image: labs-sample
      container_name: ubuntu
      privileged: true
#      ports:
#      - 80:80
      command: tail -f /dev/null
      volumes:
        - ./labs-src/ubuntu/etc/wireguard/:/etc/wireguard/
      networks:
        my-network:
          ipv4_address: 167.48.0.3



  ubuntu1: 
      image: labs-sample
      container_name: ubuntu1
      privileged: true
      volumes:
        - ./labs-src/ubuntu1/etc/wireguard/:/etc/wireguard/
#      ports: 
#      - 80:80
      command: tail -f /dev/null
      networks:
        my-network:
          ipv4_address: 167.48.0.4
 

networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 167.48.0.0/16
      

