FROM ubuntu:latest
WORKDIR /
RUN apt update
RUN apt upgrade -y
RUN apt-get update
RUN apt-get upgrade -y
RUN apt install net-tools iputils-ping nano netcat-traditional htop -y
RUN apt install apache2 -y
ENV DEBIAN_FRONTEND=noninteractive
RUN apt install php -y
RUN apt install libapache2-mod-php php-mysql -y
RUN apt install openssh-server -y
RUN apt install wireguard-tools -y
RUN apt install iproute2 -y
RUN apt install iptables -y
RUN apt install sudo -y
RUN sed -i 's/short_open_tag = .*/short_open_tag = On/' /etc/php/8.3/apache2/php.ini
RUN sed -i 's/short_open_tag = .*/short_open_tag = On/' /etc/php/8.3/cli/php.ini
RUN apt install openjdk-17-jdk nodejs gcc nmap dnsutils npm -y

RUN apt install screen -y

# install mongosh and its dependencies
RUN apt update && apt install -y curl gnupg  
RUN echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
RUN curl -fsSL https://pgp.mongodb.com/server-6.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-server-6.0.gpg
RUN apt update && apt install mongodb-mongosh -y

COPY 'init.sh' /root/
RUN chmod 777 /root/init.sh