version: latest
services:
  wireguard: 
    image: wireguard
    container_name: wireguard
    privileged: true
    volumes:
      - ./config/wg_confs:/etc/wireguard/
      - ./config:/config
    ports: 
      - 44556:44556/udp
    networks:
      my-network:
        ipv4_address: 167.48.0.2
        
  ubuntu:
      image: labs-sample
      container_name: ubuntu
      privileged: true
    #  ports:
    #  - 80:80
      command: tail -f /dev/null
      volumes:
        - ./labs-src/ubuntu/wireguard-conf/:/etc/wireguard/
      networks:
        my-network:
          ipv4_address: 167.48.0.4

networks:
  my-network:
    ipam:
      driver: default
      config:
        - subnet: 167.48.0.0/16
      

