FROM ubuntu:latest
WORKDIR /
RUN apt update
RUN apt upgrade -y
RUN apt install net-tools iputils-ping nano netcat htop -y
RUN apt install apache2 -y
ENV DEBIAN_FRONTEND noninteractive
RUN apt install php -y
RUN apt install libapache2-mod-php php-mysql -y
RUN apt install openssh-server -y
RUN ln -s /var/www/html ~/htdocs
RUN apt install wireguard-tools -y
RUN apt install iproute2 -y
