FROM ubuntu:latest
WORKDIR /
RUN apt update
RUN apt upgrade -y
ENV DEBIAN_FRONTEND noninteractive
RUN apt install apache2 libapache2-mod-php php-mysql -y
RUN sed -i 's/short_open_tag = .*/short_open_tag = On/' /etc/php/8.1/apache2/php.ini
RUN sed -i 's/short_open_tag = .*/short_open_tag = On/' /etc/php/8.1/cli/php.ini
RUN sed -i 's/short_open_tag = .*/short_open_tag = On/' /etc/php/8.1/cli/php.ini
RUN sed -i 's/Listen 80/Listen 8080/' /etc/apache2/ports.conf
RUN rm /var/www/html/index.html
COPY adminer.php /var/www/html/index.php
COPY adminer.css /var/www/html/adminer.css
COPY 'init.sh' /
RUN chmod 777 /init.sh
