#!/opt/homebrew/bin/php

<?php

function mysqlStatus(){
    $mysql_info = exec("docker inspect -f '{{.State.Running}}' mysql", $output, $return_var);
    if($return_var == 0 and $output[0] == 'true'){
        return true;
    }
    else{
        return false;
    }
}

function validate_credentials($user, $pass){
    system("docker exec mysql mysql -u $user -p$pass", $out);
    if($out == 0){
        return true;
    } else {
        return false;
    }
}


$mysql_username = 'root';
$mysql_password = 'umar1234';

$mysql_backup_location = '/opt/homebrew/websites/labs/workspace/labs-core/mysql-data';
$mysql_backup_log = '/opt/homebrew/websites/labs/workspace/labs-core/mysql-backup';

if(mysqlStatus() == true and validate_credentials($mysql_username, $mysql_password) == true){
    system("docker exec mysql mysqldump -u $mysql_username -p$mysql_password --all-databases > $mysql_backup_location/mysql-data.sql", $out);
    
    if($out == 0){
        system("export TZ=Asia/Kolkata && echo Last MySQL backup done on: `date` > $mysql_backup_log/last-backup.txt");
    }else{
        system("export TZ=Asia/Kolkata && echo Last MySQL backup error: `date` > $mysql_backup_log/mysql-backup-error.txt");
    }
} else {
    system("export TZ=Asia/Kolkata && echo MySQL was not up on: `date` > $mysql_backup_log/mysql-down-error.txt");
}

